apiVersion: v1
kind: Service
metadata:
  name: retail-app-service
  namespace: retail-app
  labels:
    app: retail-app
spec:
  type: LoadBalancer
  selector:
    app: retail-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800